require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
