default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: 5432

development:
  <<: *default
  database: e_social_twitter_api_development

test:
  <<: *default
  database: e_social_twitter_api_test

production:
  url: <%= ENV["MY_APP_DATABASE_URL"] %>
